### ISSUE TITLE
gvim "required" as a dependency for xschem

### ISSUE THREAD

**Issue by piledriven1** [HenryAEvans/EE431_Toolchain#7]
The wonderful minds at xschem have hard-coded gvim for use when editing the netlist. When opening the netlist, there is an error when going trying to edit the netlist when going to using the dropdown via Simulation > Edit Netlist.

Can you add vim-gtk3 please? Thanks all.

**Comment by HenryAEvans** [comment]
PR has been merged. Give us a couple of days to rebuild the docker hub image, or you can build it locally yourself.
